# EvoWorld Simulation Configuration

# Database Configuration
[database]
host = "localhost"
port = 5432
database = "evoworld"
username = "evoworld"
password = "evoworld_password"
# Use environment variable if available, otherwise use default
url = "${DATABASE_URL:-postgresql://evoworld:evoworld_password@localhost:5432/evoworld}"

# Analytics Configuration
[analytics]
enabled = true
collection_interval = 100
retention_days = 30

# Simulation Configuration
[simulation]
tick_rate = 10.0
max_humanoids = 1000
save_interval = 100
log_interval = 10

# World Configuration
[world]
world_size = [1000, 1000]
terrain_seed = 42
initial_population = 100
climate_zones = 5
resource_density = 0.3
weather_variability = 0.1

# AI Configuration
[ai]
behavior_complexity = 5
learning_rate = 0.1
memory_capacity = 100
decision_frequency = 1.0

# WebSocket Configuration
[websocket]
host = "127.0.0.1"
port = 8080
max_connections = 10